spring.application.name=api-gateway
server.port=8080

# config Gateway to report eureka server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# config Gateway to discover service
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

#  auth server ,ad? ruler here: